-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 21:21:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema littlelemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema littlelemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `littlelemon` DEFAULT CHARACTER SET utf8 ;
USE `littlelemon` ;

-- -----------------------------------------------------
-- Table `littlelemon`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Customers` (
  `CustomerID` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Countries` (
  `CountryID` INT NOT NULL AUTO_INCREMENT,
  `Country` VARCHAR(45) NOT NULL,
  `CountryCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CountryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Cities` (
  `CityID` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Addresses` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  `PostalCode` VARCHAR(45) NOT NULL,
  `CityID` INT NOT NULL,
  `CountryID` INT NOT NULL,
  `CustomerID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AddressID`),
  INDEX `addresses_city_id_fk_idx` (`CityID` ASC) VISIBLE,
  INDEX `addresses_country_id_fk_idx` (`CountryID` ASC) VISIBLE,
  INDEX `addresses_customer_id_fk_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `addresses_city_id_fk`
    FOREIGN KEY (`CityID`)
    REFERENCES `littlelemon`.`Cities` (`CityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `addresses_country_id_fk`
    FOREIGN KEY (`CountryID`)
    REFERENCES `littlelemon`.`Countries` (`CountryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `addresses_customer_id_fk`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `littlelemon`.`Customers` (`CustomerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CourseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Cuisines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Cuisines` (
  `CuisineID` INT NOT NULL AUTO_INCREMENT,
  `CuisineName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CuisineID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Starters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Starters` (
  `StarterID` INT NOT NULL AUTO_INCREMENT,
  `StarterName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StarterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Desserts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Desserts` (
  `DessertID` INT NOT NULL AUTO_INCREMENT,
  `DessertName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DessertID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Drinks` (
  `DrinkID` INT NOT NULL AUTO_INCREMENT,
  `DrinkName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DrinkID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Sides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Sides` (
  `SideID` INT NOT NULL AUTO_INCREMENT,
  `SideName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SideID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Orders` (
  `OrderID` VARCHAR(45) NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  `CostPrice` DECIMAL(6,2) NOT NULL,
  `SellingPrice` DECIMAL(6,2) NOT NULL,
  `Quantity` INT NOT NULL,
  `Discount` DECIMAL(6,2) NOT NULL,
  `CustomerID` VARCHAR(45) NOT NULL,
  `CourseID` INT NOT NULL,
  `CuisineID` INT NOT NULL,
  `StarterID` INT NOT NULL,
  `DessertID` INT NOT NULL,
  `DrinkID` INT NOT NULL,
  `SideID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `orders_customer_id_fk_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `orders_course_id_fk_idx` (`CourseID` ASC) VISIBLE,
  INDEX `orders_cuisine_id_fk_idx` (`CuisineID` ASC) VISIBLE,
  INDEX `orders_starter_id_fk_idx` (`StarterID` ASC) VISIBLE,
  INDEX `orders_dessert_id_fk_idx` (`DessertID` ASC) VISIBLE,
  INDEX `orders_drink_id_fk_idx` (`DrinkID` ASC) VISIBLE,
  INDEX `orders_side_id_fk_idx` (`SideID` ASC) VISIBLE,
  CONSTRAINT `orders_customer_id_fk`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `littlelemon`.`Customers` (`CustomerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_course_id_fk`
    FOREIGN KEY (`CourseID`)
    REFERENCES `littlelemon`.`Courses` (`CourseID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_cuisine_id_fk`
    FOREIGN KEY (`CuisineID`)
    REFERENCES `littlelemon`.`Cuisines` (`CuisineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_starter_id_fk`
    FOREIGN KEY (`StarterID`)
    REFERENCES `littlelemon`.`Starters` (`StarterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_dessert_id_fk`
    FOREIGN KEY (`DessertID`)
    REFERENCES `littlelemon`.`Desserts` (`DessertID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_drink_id_fk`
    FOREIGN KEY (`DrinkID`)
    REFERENCES `littlelemon`.`Drinks` (`DrinkID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_side_id_fk`
    FOREIGN KEY (`SideID`)
    REFERENCES `littlelemon`.`Sides` (`SideID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Deliveries` (
  `DeliveryID` INT NOT NULL AUTO_INCREMENT,
  `DeliveryDate` DATETIME NOT NULL,
  `DeliveryFee` DECIMAL(6,2) NOT NULL,
  `AddressID` INT NOT NULL,
  `OrderID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DeliveryID`),
  INDEX `deliveries_address_id_fk_idx` (`AddressID` ASC) VISIBLE,
  INDEX `deliveries_order_id_fk_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `deliveries_address_id_fk`
    FOREIGN KEY (`AddressID`)
    REFERENCES `littlelemon`.`Addresses` (`AddressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `deliveries_order_id_fk`
    FOREIGN KEY (`OrderID`)
    REFERENCES `littlelemon`.`Orders` (`OrderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemon`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemon`.`Payments` (
  `PaymentID` INT NOT NULL AUTO_INCREMENT,
  `SellingPriceAfterDiscount` DECIMAL(6,2) NOT NULL,
  `DeliveryFee` DECIMAL(6,2) NOT NULL,
  `AmountPaid` DECIMAL(6,2) NOT NULL,
  `OrderID` VARCHAR(45) NOT NULL,
  `DeliveryID` INT NOT NULL,
  PRIMARY KEY (`PaymentID`),
  INDEX `payments_order_id_fk_idx` (`OrderID` ASC) VISIBLE,
  INDEX `payments_delivery_id_fk_idx` (`DeliveryID` ASC) VISIBLE,
  CONSTRAINT `payments_order_id_fk`
    FOREIGN KEY (`OrderID`)
    REFERENCES `littlelemon`.`Orders` (`OrderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `payments_delivery_id_fk`
    FOREIGN KEY (`DeliveryID`)
    REFERENCES `littlelemon`.`Deliveries` (`DeliveryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
